### ISSUE TITLE
Documentation does not capture different addresses in R_RISCV_PCREL_HI20 and R_RISCV_PCREL_LO12_[IS]

### ISSUE THREAD

**Issue by grant-hub** [riscv/riscv-elf-psabi-doc#102]
The documentation says the following about the PCREL relocations:

> 23	R_RISCV_PCREL_HI20	PC-relative reference	%pcrel_hi(symbol) (U-Type)
> 24	R_RISCV_PCREL_LO12_I	PC-relative reference	%pcrel_lo(symbol) (I-Type)
> 25	R_RISCV_PCREL_LO12_S	PC-relative reference	%pcrel_lo(symbol) (S-Type)

This lead me to believe that the same data address would be referenced in the HI20 as the LO12.

However, upon compiling an assembly file containing an access to a global of the following form:

`ld t4,my_global+8`

and inspecting the relocation table generated with elfdump, I discovered that the symbols referenced by the PCREL_HI20 and the PCREL_LO12_I relocations were different:

```
entry: 4
        r_offset: 0x10
        r_info: 0x400000017
        r_addend: 8

entry: 5
        r_offset: 0x10
        r_info: 0x33
        r_addend: 8

entry: 6
        r_offset: 0x14
        r_info: 0x2900000018
        r_addend: 0
```

Looking at these symbols, the one referenced by the PCREL_HI20 was the global:

```
entry: 4
        st_name: my_global
        st_value: 0
        st_size: 16
        st_info: STT_OBJECT STB_LOCAL
        st_shndx: 3
```

But the one referenced by the PCREL_LO12_I was a label into the text section:

```
entry: 45
        st_name: .L0 
        st_value: 0x44
        st_size: 0
        st_info: STT_NOTYPE STB_LOCAL
        st_shndx: 1
```

It appears that the PCREL_HI20 part refers to the data address being accessed, while the PCREL_LO12 part refers to a label indicating the start PC being accessed relative to. After going on this journey of discovery, I did find that the examples in the RISCV asm documentation could have given me this clue, although the example that describes this behavior points it out very subtly:

```
1:      auipc a0, %pcrel_hi(msg)    # load msg(hi)
        addi a0, a0, %pcrel_lo(1b)  # load msg(lo)

```
It's pretty easy to not notice that 1b is in pcrel_lo rather than msg, especially if you weren't looking for this piece of information specifically.

Would it be possible to update the documentation to indicate this behavior more clearly?

**Comment by aswaterman** [comment]
The description in https://github.com/riscv/riscv-elf-psabi-doc/blob/master/riscv-elf.md#pc-relative-symbol-addresses seems to convey this point:

"The R_RISCV_PCREL_LO12_I or R_RISCV_PCREL_LO12_S relocations contain a label pointing to an instruction with a R_RISCV_PCREL_HI20 relocation entry that points to the target symbol:

At label: R_RISCV_PCREL_HI20 relocation entry ⟶ symbol
R_RISCV_PCREL_LO12_I relocation entry ⟶ label"

**Comment by grant-hub** [comment]
OK, this may have been me not reading this document closely enough.

However, the table does seem to indicate that %pcrel_lo contains the same symbol as the %pcrel_hi:

```
23	R_RISCV_PCREL_HI20	PC-relative reference	%pcrel_hi(symbol) (U-Type)
24	R_RISCV_PCREL_LO12_I	PC-relative reference	%pcrel_lo(symbol) (I-Type)
25	R_RISCV_PCREL_LO12_S	PC-relative reference	%pcrel_lo(symbol) (S-Type)
```

Would it be possible to update the table entry to make the wording slightly different between the two? Maybe %pcrel_lo(text_addr_using_pcrel_hi) or something like that? If I had seen something like that, it may have clued me in that there was something going on with the relationship between these two relocations I did not fully understand.

**Comment by aswaterman** [comment]
Agreed.
