### ISSUE TITLE
Document in-memory representation of _Bool

### ISSUE THREAD

**Issue by gnzlbg** [riscv/riscv-elf-psabi-doc#103]
The in-memory representation of _Bool is not documented anywhere. 

The SysV64 ABI specifies it as follows:

> Booleans, when stored in a memory object, are stored as single byte objects the value
of which is always 0 (false) or 1 (true).

Which section of the ABI would be appropriate to add this type of wording ?

Some parts of the ISA, e.g., the RISC-V Vector ISA, use 0 for false, and ~0 for true. It might be saner to try to make the representation of _Bool to match all contexts, and use ~0 for true everywhere. ~0 is a mask that selects all bits. Being able to just do a "logical and" with _Bool to select all or no bits would be quiet useful and elegant.

**Comment by jim-wilson** [comment]
Which exact SysV64 ABI are you referring to?  Please give a reference, such as a URL.

The ISO C standard says that the only correct values for _Bool and 0 and 1.  Please do not confuse the vector extension hardware with the ISO C standard.
