### ISSUE TITLE
Document _Alignof(max_align_t)

### ISSUE THREAD

**Issue by gnzlbg** [riscv/riscv-elf-psabi-doc#104]
The "Defualt ABIs and C type sizes" section does not document the value of `_Alignof(max_align_t)`, which is implementation-defined and part of the platform ABI.

`long double` has an alignment requirement of 16, which forces `_Alignof(max_align_t) >= 16` on the 32-bit and 64-bit ISAs. 

All memory allocations returned by `malloc` for sizes `>= _Alignof(max_align_t)` need to be aligned to a `_Alignof(max_align_t)` boundary, so from this POV, it makes sense to pick it "as large as necessary, as small as possible".

The SysV 32 and 64-bit ABIs set `_Alignof(max_align_t) == 16`, and this would also make sense here AFAICT. 

The only reason to pick a higher value is if we plan to have types in the ISA with a fundamental alignment larger than 16 bytes according to the C standard.

**Comment by jim-wilson** [comment]
Which exact SysV ABIs are you referring to here?  Give a URL please.

max_align_t greater than the stack alignment is problematic.  Our stack alignment for ilp32{,f,d} and lp64{,f,d} is 16, and it is 4 for ilp32e.  GCC reports 16 for _Alignof(max_align_t) for all of these ABIs, including ilp32e, but we already know that the ilp32e ABI is broken and are planning to fix it with a new EABI.  Anyways, documenting it as 16 looks correct.

**Comment by gnzlbg** [comment]
> Which exact SysV ABIs are you referring to here?

The  x86-64 psABI and the Intel386 psABI, I'll see if I can find a link. 

> GCC reports 16 for _Alignof(max_align_t) for all of these ABIs, including ilp32e,

Well, GCC has to do that for the Intel386 psABI. `_Alignof(max_align_t)` is defined as the largest alignment requirement of a "fundamental" type, and the Intel386 psABI supports the fundamental type `long float` which has an alignment requirement of 16. So AFAICT GCC hands are tied. 

The only way to lower the value of `_Alignof(max_align_t)` for an ABI is, per definition, to lower the largest alignment requirement of the fundamental types in that ABI.

**Comment by jim-wilson** [comment]
I would suggest
    http://refspecs.linuxfoundation.org/elf/
which has multiple SVR4 ABIs including the i386 and x86_64 ones.  I don't see a reference to max_align_t in the x86_64 one, but I need some time to look at this.

The i386 port does stack aligning when necessary, but the RISC-V port does not, which is why the ilp32e ABI is broken.

Anyways, this suggestion is uncontroversial.  16 is correct.  Assuming we need to document this.
