### ISSUE TITLE
ABI-mandated location for dynamic linker

### ISSUE THREAD

**Issue by kraj** [riscv/riscv-elf-psabi-doc#114]
Some distributions do have `usrmerge` feature in this case the linker is installed into `/usr/lib/ld-linux-riscv64-lp64d.so.1`, I was looking for some ABI directions e.g. on aarch64 its explicitly mentioned that it should remain in `/lib` but I could not find any directions for ABI spec for RISC-V. What will be the recommendation here?

**Comment by aswaterman** [comment]
I think it needs to remain in /lib, as the absolute path to the dynamic
linker is hardcoded into dynamically linked executables.

**Comment by jim-wilson** [comment]
usrmerge means /lib is a symbolic link to /usr/lib.  And similarly with /bin and /sbin.  This eliminates a few dirs in the filesystem root, and eliminates some duplication.  So if ld.so is in /usr/lib, it will still be accessible via the symbolic link from /lib.

I don't think we have any formal docs for this.  There are some comments in the glibc port that imply that ld.so is in /lib.  See for instance in sysdeps/unix/sysv/linux/riscv/dl-cache.h the add_system_dir comment.  And we have only two supported names for ld.so which are in the sysdeps/unix/sysv/linux/riscv/shlib-versions file, though I expect that the rv32 glibc patch will add two more.

I think putting ld.so in /usr/lib and having the /lib symlink is OK, though if you want to drop the /lib symlink that will cause trouble.  That probably requires glibc changes, and gcc changes, and maybe changes to other stuff too.

**Comment by jrtc27** [comment]
This is up to the OS. FreeBSD always has its linker as /libexec/ld-elf.so.1 (with the kernel mapping that to /libexec/ld-elf32.so.1 at run time when running 32-bit binaries on 64-bit systems), and Linux/glibc uses /lib/ld-linux-riscv$XLEN-$ABI.so.1. Some older psABIs mandated linker locations but this is just an annoying waste of time that just ends up being ignored because it doesn't achieve anything useful.

**Comment by kito-cheng** [comment]
Just more note about that, different libc implementation might use different path for dynamic linker too, for example, musl using `/lib/ld-musl-riscv[32|64][|-sp|-dp].so.1` as its dynamic linker path.

**Comment by kraj** [comment]
letting OSes chose it is fine by me. But perhaps it would be helpful to have a pointer for users on this.

**Comment by jrtc27** [comment]
> letting OSes chose it is fine by me. But perhaps it would be helpful to have a pointer for users on this.

I mean, users shouldn't need to care, the toolchain is meant to set it correctly for you, and we're not in the business of listing all C implementations out there. Ultimately it's up to your OS (or libc implementation) to document this somewhere if it deems that worthwhile.
