### ISSUE TITLE
ILP32E and Variadic Arguments

### ISSUE THREAD

**Issue by lenary** [riscv/riscv-elf-psabi-doc#125]
I would like some clarity around variadic arguments on ILP32E. 

At the moment, the [ILP32E Calling Convention](https://github.com/riscv/riscv-elf-psabi-doc/blob/master/riscv-elf.md#ilp32e-calling-convention) does not contain any exceptions for the variadic argument behaviour in the base integer calling convention.

The Base integer calling convention says the following about variadic arguments, none of which is predicated on the current stack alignment:
> In the base integer calling convention, variadic arguments are passed in the same manner as named arguments, with one exception. Variadic arguments with 2✕XLEN-bit alignment and size at most 2✕XLEN bits are passed in an aligned register pair (i.e., the first register in the pair is even-numbered), or on the stack by value if none is available. After a variadic argument has been passed on the stack, all future arguments will also be passed on the stack (i.e. the last argument register may be left unused due to the aligned register pair rule).

During the implementation of ILP32E in LLVM, it was noted that we were not required to use aligned pairs for these cases, but I'm not sure how the specification supports this claim as currently written.

**Comment by lenary** [comment]
Ah, I see what's going on: The "aligned pair" rule is to ensure that spills of the registers containing those arguments remain aligned, and the issue is that neither GCC or LLVM can actually guarantee this alignment (for spills) in practice on ILP32E, because the stack is only 4-byte aligned.

**Comment by ShivaChen** [comment]
Yes, exactly. Given that neither GCC or LLVM can guarantee the alignment of double load/store for ilp32e ABI with feature D in https://reviews.llvm.org/D70401#inline-645653 test case, I was thinking that should we change the ilp32e alignment to 8 with "aligned pair"? So we can handle the case with ilp32e ABI and feature D correctly and avoid frequently re-alignment from 4 to 8 when there is a double value on the stack. Any thoughts?

**Comment by jim-wilson** [comment]
Changing the ilp32e alignment is an ABI break which is undesirable.  Is there anyone that actually needs ilp32ed support?  The simplest and best solution is to just give an error.  Which I think binutils and gcc already do, as we never added ilp32e FP support.  The second best solution is to finish the proposed eabi and get the alignment constraints right there.  And I'd rank changing the current ilp32e ABI as the worst solution.

**Comment by lenary** [comment]
I agree that changing the type sizes and alignments is a breaking change for `ilp32e` and should be avoided. I am happy to prepare a PR for the psABI spec to dissuade people from using `ilp32e` with `rv32i*d`
