### ISSUE TITLE
Order of arguments passed on the stack; value of stack pointer on function entry

### ISSUE THREAD

**Issue by konrad-schwarz** [riscv/riscv-elf-psabi-doc#135]
I can't see where the document specifies in which order arguments passed on the stack are stored.  I think that arguments are stored in ascending order on the stack (because of the stack alignment restriction), which is somewhat at variance to the statement that the "stack grows downwards" -- a naive code generator operating from left to write that pushes the arguments would store the arguments in descending order, with the leftmost argument having the highest address.

Similarly, I can't see where the location the stack points to at function entry is specified.  I think the ABI specifies what ARM terms a "full descending" stack, i.e., on function entry, the stack pointer points to (a 128-byte aligned) block of allocated stack space, with any stack-passed arguments located starting at offset 0 from the stack pointer.

**Comment by jim-wilson** [comment]
In gcc terminology, stack grows downwards means the initial stack pointer value starts at the top of the stack memory region, every function creates a frame by subtracting the frame size from the stack pointer, and then values in the frame are referenced by positive offsets from the stack pointer.  It is uncommon, but there are targets that do this the other way, by putting the sp at the bottom of stack memory and adding to the sp to create a frame.

Within a frame, arguments are allocated left to right with increasing offsets.  I think this is how pretty much all ABIs work on targets without push/pop instructions.  The first argument on the stack is at offset 0 from the sp at function entry.

Yes, some of this stuff could be specified better.

**Comment by aswaterman** [comment]
I merged #136, so closing.
