### ISSUE TITLE
Clarify basic wording

### ISSUE THREAD

**Issue by RincewindsHat** [riscv/riscv-elf-psabi-doc#146]
Hello,
I am newish to the whole topic and have some difficulties with some of the term.
For one: what does psABI stand for?

**Comment by jim-wilson** [comment]
This is SVR4 UNIX terminology.  gABI is the generic ABI.  psABI is the processor specific ABI.  ABI is Application Binary Interface.  The full Unix ABI is gABI+psABI.  The gABI defines the processor independent parts of the ABI: the ELF object file format, how shared libraries, work, etc.  There are multiple psABIs, one for each architecture, and covers processor specific stuff.  Currently, we use the same ABI for Unix and embedded elf.  There are plans to add a separate embedded elf ABI later.
