### ISSUE TITLE
Reserve a subset of e_flags for non-standard extensions

### ISSUE THREAD

**Issue by jrtc27** [riscv/riscv-elf-psabi-doc#157]
Currently the specification says:

> Until such a time that the Reserved bits (0xffffffe0) are allocated by future versions of this specification, they shall not be set by standard software.

This leaves no bits free for use by non-standard extensions. On [CHERI-RISC-V] we currently allocate two bits (although we'd like to make one of those redundant at some point), and those were chosen to be 0x00010000 and 0x00020000 in order to leave space for new bits allocated in the base ABI, whilst also leaving space for us to allocate new bits for CHERI-RISC-V if/when needed (and being at a nice round boundary). The RISC-V attributes section helps alleviate contention on the ELF flags, but when defining drastically-different ABIs it is useful to have bits in e_flags for that, as that is generally what dynamic loaders have to hand, with RISC-V attributes parsing a whole pile of RISC-V-specific complexity that you don't want in such crucial low-level code.

Please define a range of bits reserved for use by non-standard extensions. Ideally this would overlap with our allocated bits, but if it doesn't make sense to do so then we can perform a (painful) migration to newer standards-conforming flag bits.

[CHERI-RISC-V]: https://github.com/CTSRD-CHERI/cheri-elf-psabi/blob/master/riscv.md#file-header

**Comment by lenary** [comment]
It seems a proactive measure to do this, and would allow developers to work on prototypes of other additions to the psABI (such as the compact code model, or FDPIC).

I'm unsure how many bits to reserve for custom users - it would be good to work out what is reasonable but I don't have the time to quickly scan other psABIs now. I suggest either the highest 8 or 16 bits to be used, as those seem like 'round' numbers, but as I said, I'm unsure.

I would like to hear @jim-wilson and @ebahapo's opinions.

**Comment by jrtc27** [comment]
Yeah, 16 seems quite generous, but 8 could be a bit tight depending on what you're doing. I went with the first two bits of the higher 16 bits because, at the time, RISC-V attributes support didn't exist in LLVM so I thought I might need rather more, and it was a "nice" way to split it. I think it depends how many more bits are earmarked for future _standard_ extensions. I anticipate wanting about 5 bits, so 8 would be fine for us, just annoying to shift from bit 16+ to bit 24+.

**Comment by aswaterman** [comment]
I think 16 is too many.  We can always turn more reserved bits into custom bits in the future, but we can't go backwards.  Bits 24-31 seems OK to me, if possibly on the overly generous side.

**Comment by ebahapo** [comment]
Typically psABIs define just a handful (less than 4, but often 0) of bits and make about as many for non standard use.  

I agree with @aswaterman, 16 bits seem too many.  The top 8 bits seem generous, yet sensible. If more bits become really, really necessary, they can be allocated from the MSB.  

Methinks that if more bits are necessary, then special sections should be considered instead.  The `e_flags` should be primarily used for simple and fast processes, like program loading and stuff, when parsing bytes or walking tables is not desirable.
