### ISSUE TITLE
DWARF numbers for vector registers.

### ISSUE THREAD

**Issue by Hsiangkai** [riscv/riscv-elf-psabi-doc#159]
I propose to add the DWARF numbers for vector registers.

Dwarf Number | Register Name | Description
---|---|---
65-96 | v0-v31 | Vector Registers

**Comment by jim-wilson** [comment]
Another option might be 96 to 127 which makes the arithmetic easiest for humans.  That leaves 65 to 95 unused, but we may find a future use for those numbers.

**Comment by Hsiangkai** [comment]
I am fine to map v0-v31 to 96-127.

**Comment by kito-cheng** [comment]
Allocate 96-127 for vector register LGTM, could you made a PR for this?

**Comment by kito-cheng** [comment]
It's merged so I close this issue
