### ISSUE TITLE
Why RISC-V uses only a0-a1 as return value, other than all a0-a7 in standard calling convention?

### ISSUE THREAD

**Issue by luojia65** [riscv/riscv-elf-psabi-doc#187]
In some programming languages we may transfer return values which may exceed 2*XLEN length, and by now these functions will require a stack position, and fill value into it. Will it be more simple to use all a0-a7 registers as return values?

Just to raise a question, feel free to discuss :)

**Comment by jrtc27** [comment]
Larger values typically mean complex structs. The bigger the struct, or the more complicated its layout, the more instructions you need to pack it into registers / unpack it into memory, so beyond a certain point it's better to just have it in memory with the right layout. Returning 2*XLEN-sized structs in registers is extremely common across ABIs as a happy-ish middle-ground. This is not a part of the ABI that can be changed, either, as it is an ABI break that will cause real-world compiled code to no longer be compatible.

**Comment by luojia65** [comment]
Thank you @jrtc27 :)
