### ISSUE TITLE
LICENSE file needs full CC-BY-4.0 license text

### ISSUE THREAD

**Issue by jjscheel** [riscv/riscv-elf-psabi-doc#193]
Good community practice includes the full license text in the file instead of linking to it.

Unless someone has an objection, I'll update the file with the text (like the [ISA LICENSE file](https://github.com/riscv/riscv-isa-manual/blob/master/LICENSE)) in the next couple days. Please let me know if you have any concerns.

@aswaterman, I'd love your guidance on how you'd like this to occur.  would you want to take care of this or should I?  If you'd prefer me to handle, do you prefer a PR or a simple commit to main?

**Comment by aswaterman** [comment]
@jjscheel Assuming you have write permissions, feel free to push the license to master.  If not, feel free to make a PR and I'll merge it.

**Comment by jjscheel** [comment]
@aswaterman, done.   Let me know if you see any problems.

Closing.
