### ISSUE TITLE
Claiming the calling convention

### ISSUE THREAD

**Issue by sorear** [riscv/riscv-elf-psabi-doc#2]
I've just done a bunch of tests to nail this down for the libffi port, so I should probably document this very soon.

**Comment by aswaterman** [comment]
For anyone else paying attention to this issue tracker, the new proposal is here: https://github.com/riscv/riscv-elf-psabi-doc/blob/e0d301cddcafae07981ada8dca2b34d8349e53d0/riscv-elf.md#procedure-calling-convention

**Comment by jrtc27** [comment]
Bar potential clarifications this was resolved long ago.
