### ISSUE TITLE
Bit fields are unspecified

### ISSUE THREAD

**Issue by asb** [riscv/riscv-elf-psabi-doc#20]
The AArch64 AAPCS and x86-64 psABI both make an effort to standardise bit field representation. I don't know how much code is out there that exposes bit fields in its public ABI, but it may be worth specifying something sensible here.

**Comment by palmer-dabbelt** [comment]
I'm not convinced we're doing something sane here -- it looks like we're 32-bit aligned unless the base type is 8 bits or the bit field width is larger than 32.  I think we should at least be consistent about whether we align to bit field length or to the base type length.

@aswaterman @sorear Thoughts?

````
palmer gamma02 ~ $ cat test.c 
#include <stdint.h>

struct bf {
	uint32_t a: 1;
	uint32_t b;
	uint32_t c: 3;
	uint32_t d;
	uint64_t e: 1;
	uint32_t f;
	uint64_t g: 32;
	uint32_t h;
	uint64_t i: 64;
	uint32_t j;
	uint8_t k: 1;
	uint8_t l;
};

void func(uint64_t);
extern struct bf bf;

uint32_t main() {
	func(bf.a);
	func(bf.b);
	func(bf.c);
	func(bf.d);
	func(bf.e);
	func(bf.f);
	func(bf.g);
	func(bf.h);
	func(bf.i);
	func(bf.j);
	func(bf.k);
	func(bf.l);
}
palmer gamma02 ~ $ riscv64-unknown-linux-gnu-gcc test.c -O3 -S -o -
	.file	"test.c"
	.option nopic
	.section	.text.startup,"ax",@progbits
	.align	2
	.globl	main
	.type	main, @function
main:
	add	sp,sp,-16
	sd	s0,0(sp)
	lui	s0,%hi(bf)
	lbu	a0,%lo(bf)(s0)
	sd	ra,8(sp)
	add	s0,s0,%lo(bf)
	and	a0,a0,1
	call	func
	lwu	a0,4(s0)
	call	func
	lbu	a0,8(s0)
	and	a0,a0,7
	call	func
	lwu	a0,12(s0)
	call	func
	lbu	a0,16(s0)
	and	a0,a0,1
	call	func
	lwu	a0,20(s0)
	call	func
	lwu	a0,24(s0)
	call	func
	lwu	a0,28(s0)
	call	func
	ld	a0,32(s0)
	call	func
	lwu	a0,40(s0)
	call	func
	lbu	a0,44(s0)
	and	a0,a0,1
	call	func
	lbu	a0,45(s0)
	call	func
	ld	ra,8(sp)
	ld	s0,0(sp)
	add	sp,sp,16
	jr	ra
	.size	main, .-main
	.ident	"GCC: (GNU) 6.1.0"
````

**Comment by aswaterman** [comment]
It looks like rv64 matches aarch64 and x86-64 in this example, which is sane enough for me.  I propose keeping as-is and documenting the behavior.

**Comment by palmer-dabbelt** [comment]
If it matches then we should keep it -- plus, that makes it easier to document.  @sorear assuming you're OK with this, can you write it up?

**Comment by asb** [comment]
Does anyone have time to document what GCC actually does for bit fields?

**Comment by aswaterman** [comment]
I'll take a stab at it

**Comment by aswaterman** [comment]
Not sure if this is everything, but it is a start:

Bitfields are packed in little-endian fashion.  A bitfield that would span the alignment boundary of its integer type is padded to begin at the next alignment boundary.  For example, ```struct { int x : 10; int y : 12; }``` is a 32-bit type with ```x``` in bits 9-0, ```y``` in bits 21-10, and bits 31-22 undefined.  By contrast, ```struct { short x : 10; short y : 12; }``` is a 32-bit type with ```x``` in bits 9-0, ```y``` in bits 27-16, and bits 31-28 and 15-10 undefined.

**Comment by jim-wilson** [comment]
On Fri, Jan 12, 2018 at 2:14 PM, Andrew Waterman <notifications@github.com>
wrote:

> Not sure if this is everything, but it is a start:
>
> Bitfields are packed in little-endian fashion. A bitfield that would span
> the alignment boundary of its integer type is padded to begin at the next
> alignment boundary. For example, struct { int x : 10; int y : 12; } is a
> 32-bit type with x in bits 9-0, y in bits 21-10, and bits 31-22
> undefined. By contrast, struct { short x : 10; short y : 12; } is a
> 32-bit type with x in bits 9-0, y in bits 27-16, and bits 31-28 and 15-10
> undefined.
>
It looks reasonable to me.  The GCC docs for implementation-defined
bit-field behavior are here:

https://gcc.gnu.org/onlinedocs/gcc-7.2.0/gcc/Structures-unions-enumerations-and-bit-fields-implementation.html#Structures-unions-enumerations-and-bit-fields-implementation
An ABI only needs to specify the order of allocation for bit-fields, and
whether they can straddle a storage-unit boundary.  We can of course
specify other things if we want.

Jim

**Comment by aswaterman** [comment]
Thanks, Jim.  I'll make a PR.
