### ISSUE TITLE
Remove ILP32E ABI or flag as draft

### ISSUE THREAD

**Issue by jrtc27** [riscv/riscv-elf-psabi-doc#207]
EABI issues and RV32E remain up in the air. We should either clearly mark the ILP32E ABI as a draft so it is not regarded as official specification for the first "release" or remove it entirely and re-add it later in whatever form makes sense.

**Comment by jim-wilson** [comment]
There are people using ilp32e in shipping code, so removing it isn't an option.  I'd also argue that something that is being shipped shouldn't be marked as draft either.  Drafts can be changed in incompatible ways, but any incompatible change to ilp32e would break shipping code.  We should just accept that it is a real ABI, and deprecate when a replacement EABI becomes available.

**Comment by jrtc27** [comment]
That is unfortunate :( but I guess means there's nothing to do here. We could perhaps document that PLTs don't exist for RVE (#77).
