### ISSUE TITLE
Misleading example in floating point calling convention section

### ISSUE THREAD

**Issue by asb** [riscv/riscv-elf-psabi-doc#22]
The document currently states: "`struct { struct { float f[1]; } g[2]; int h; }` and `struct { float f; float g; int h; }` are treated the same"

There are multiple possible fixes depending on the point that is being made. Perhaps `{ struct { float f[1]; } float g[1]; int h; }` is what was intended? However regardless of whether you flatten the struct fields, this is (by my reading) always passed identically to the integer calling convention. `struct { struct { float f[1]; } int h[1]; }` would perhaps be a better example?

**Comment by aswaterman** [comment]
I'm confused, the example still looks correct to me (and gcc agrees).

**Comment by aswaterman** [comment]
That is, in the second case (in RV64), f is passed in a0[31:0], g is passed in a0[63:32], and h is passed in a1[31:0].  In the first case, g[0].f[0] is passed in a0[31:0], g[1].f[0] is passed in a0[63:32], and h is passed in a1[31:0].

**Comment by asb** [comment]
Sorry, the confusion is mine. For some reason it wasn't clear to me that the array of structs was your intent, which it obviously is. That said, perhaps an example that degrades to the integer calling convention isn't the best? Surely what you're trying to show is that the FP calling convention rules regarding a struct containing 2 fp elements, or 1fp+1int apply regardless of any nesting. Perhaps `struct { struct { float f[1]; } g[2];}` is a better example of this, which would result in two FPRs if the struct is properly flattened, but you might imagine could be passed according to the integer calling convention in a buggy implementation.

If you prefer it how it is, no big deal. I just read that example and then re-read the FP calling convention several times to try to see if I missed a way it would be handled differently with the hard FP.

**Comment by aswaterman** [comment]
Good point, I forgot the context.  It would make quite a bit more sense if the example used in the hardware FP calling convention was actually passed in FP registers.

Can you make a PR changing the examples to use 2 fp or 1 fp + 1 int, whichever you think gets the point across more clearly?
