### ISSUE TITLE
Alignment requirements of small aggregates/scalars passed on the stack should be specified

### ISSUE THREAD

**Issue by asb** [riscv/riscv-elf-psabi-doc#26]
Imagine I have a double or a struct containing a double on an RV32I system. This probably has 8-byte alignment (see #19). In the case that there are no GPRs available, will the stack slot it is written to be 4 or 8-byte aligned? (i.e. aligned according to the original type, or according to xlen).

There's a related case with a struct containing an int32 on an RV64I system. The struct has 4-byte alignment, but when I fail to allocate a GPR for it there's the choice of assigning 4-byte sized 4-byte aligned stack slot, an 8-byte size 4-byte aligned stack slot, or a 8-byte size 8-byte aligned stack slot. I think "bits past the end of an aggregate whose size in bits is not divisible by XLEN, are undefined" suggests an 8-byte stack slot, but the alignment is still unspecified.

Is the intended alignment rule max(xlen_align, object_align) for these cases?

**Comment by asb** [comment]
I should say, the second paragraph is answered by providing a clear indication that stack entries are always a multiple of XLEN bits, which would mean the alignment is always at least XLEN. [This is what the current code does of course, but we should be explicit].

**Comment by asb** [comment]
The current gcc behaviour seems to match the max(xlen_align, object_align) rule. i.e. on RV32 a struct containing an int64_t that gets passed on the stack will be 8-byte aligned, while a struct containing two int32_t that is passed on the stack will be 4-byte aligned.

**Comment by aswaterman** [comment]
Object-aligned, up to the stack alignment.
