### ISSUE TITLE
Size of standard C types should be described

### ISSUE THREAD

**Issue by asb** [riscv/riscv-elf-psabi-doc#28]
There is a table in the v2.1 spec which should be moved here. It might also be worth expanding to include a mapping of `_Complex` and `_Bool`.

The table in the v2.1 specification lists long double as 16 bytes in RV32. Is that correct given that RV32IMFDQ is specifically disallowed in the spec? Or is the idea that it's a handy way to access 128-bit fp implemented via software emulation routines?

**Comment by aswaterman** [comment]
Agreed, would be great if someone could PR this addition.
