### ISSUE TITLE
_Complex complexity

### ISSUE THREAD

**Issue by sorear** [riscv/riscv-elf-psabi-doc#3]
The AMD64 psABI specifies that `_Complex FOO` is always exactly the same as `struct { FOO re; FOO im; }`.  What is implemented in RISC-V gcc is significantly more complicated.  For instance, a `_Complex float` can be passed in three different ways on RV64G hard-float:

1. As two adjacent FPRs, like `fa4` and `fa5`, if there are 0–6 argument slots used already.  This passes them in the recoded float format.
2. Multiplexed into a single 64-bit GPR `a7` if there are 7 argument slots used.
3. Passed on the stack with 32-bit alignment if 8 or more argument slots used.

If we keep this, it'll add complexity to the psABI document, libffi, and other non-gcc programs which need to interwork with gcc such as llvm and various non-libffi ffis.  If we don't it'll require gcc changes and break compiled programs with complex number arguments (probably just LAPACK at this point).  That complexity would only be justifiable if it gave a "sufficiently large" performance benefit to "sufficiently many" programs, but I don't have a great understanding of the tradeoffs here.

Attn @aswaterman @kito-cheng because this is a gcc calling convention issue.  I am going to be filing a few more issues for complicated spots in the calling convention so we can decide which to keep.

The MVP calling convention is something close to the following:

1. All arguments which are larger than 2 * XLEN, have nontrivial copy constructors, or that are larger than XLEN and contain (transitively) a floating point field larger than FLEN, are passed in memory and replaced in the argument list by a pointer.
2. If the return value would need to be passed in memory if it were an argument, it is written into a caller-allocated buffer which becomes the first argument, and then replaced by void.
3. All arguments are expanded to a minimum of XLEN bits size and alignment with unspecified padding.
4. All arguments are placed in a notional struct, following normal alignment rules (which will always be XLEN or 2 * XLEN)
5. The first 8 * XLEN bits of the struct are passed in registers a0 - a7, except for rule (7).
6. If an argument narrower than XLEN consists of a single field of integral type, it is widened according to the sign of its type up to 32 bits and then sign extended to XLEN.
7. If FLEN >= XLEN and a [XLEN, FLEN]-aligned portion of the first 8 * XLEN of the argument list represents a field of floating point type (possibly inside a struct, but not if inside a union), that argument will be placed in the faX register of the same number instead.  If FLEN = 2 * XLEN this will leave both aX and a(X+1) empty.  (If FLEN = 4 * XLEN then this rule cannot trigger because floats will be passed in memory by rule 1.)  This rule is not applied for arguments to a variadic function which do not correspond to a formal parameter.
8. sp points at the portion of the argument struct which is not passed in registers.
9. On exit, the return value is mapped to registers as if it were the only argument of a function, following rules 3–7.

(Not 100% certain about the sign extension rule here; I'd also like to write up a rationale in a bit to see if this makes sense)

**Comment by aswaterman** [comment]
I agree that  _Complex foo should be passed the same way as struct { foo re; foo im; }.  The current behavior is a holdover from the SGI MIPS64 ABI, on which the RISC-V calling convention is based.

To avoid reducing performance, we should at the same time allow structs with 2 float32s to be passed in F registers for RV64G.  At the moment, only structs with 2 float64s will get passed in F registers; the former case is passed by reference.  I believe that is consistent with rule 7.

**Comment by sorear** [comment]
@aswaterman Do you have an example handy of a psABI that does that or is this something for me to research?

**Comment by aswaterman** [comment]
http://math-atlas.sourceforge.net/devel/assembly/mipsabi64.pdf is the best I can find.

Confusingly, it claims "A struct with only one or two floating point fields is returned in $f0 (and $f2 if
necessary). This is a generalization of the Fortran COMPLEX case." That is _not_ what MIPS GCC does.  _Complex float and _Complex double are both passed in f-registers.  A struct with 2 floats is passed by reference, and a struct with 2 doubles is passed like _Complex.

Not sure if that is just a bug in MIPS GCC that we inherited.

**Comment by aswaterman** [comment]
FWIW, AArch64 does pass struct{float;float} the same way it passes float _Complex.

**Comment by aswaterman** [comment]
I've been thinking about how to handle floating-point aggregates when FLEN != XLEN, and I'm starting to think we should just decouple integer and floating-point argument passing altogether.

Basic idea is that if an argument is a candidate to be passed in FPRs, it goes in the first available FPRs, regardless of how many integer registers have been allocated, and vice versa.  (This increases the max number of arguments in registers to 16, which is only marginally useful.)

Structs are either passed entirely in registers or entirely in memory.

Structs are passed in floating-point registers only if they consist of one or two fields that are both floating-point numbers that are both <= the ABI's FLEN.  (Things passed in FP registers are not subject to the usual 2*XLEN constraint.)

Thoughts?

**Comment by sorear** [comment]
What are the advantages and tradeoffs of this scheme?

Would a struct with 4 floats be passed in 2 GPRs on RV64G?  Is that desired?

This seems to lose a lot of the simplicity of the "conceptual struct".

I'd like to have a rule that "structs and arrays are conceptually flattened", so that `_Complex double`, `struct { double; double }`, `struct { struct { double }; double }`, `struct { double[2] }`, `struct { double; char[0]; double }` are all handled the same, as are `struct { double }` and `double`.

**Comment by aswaterman** [comment]
Main advantage is that it's simpler to describe and implement the passing of floating-point values/aggregates in floating-point registers when XLEN and FLEN differ.  In the current RV64G scheme, you can't pass struct{float;float} or float _Complex in registers without adding a special case.

A struct with 4 floats would indeed be passed in 2 GPRs on RV64G in this proposal.  That's already the case, though, and is also the case on x86-64 and AArch64.

Ancillary advantage I just discovered: my proposal appears to match AArch64 exactly.

**Comment by aswaterman** [comment]
I'm struggling to identify anything about it that's actually worse.  It does do away with the conceptual struct, but that's fine, IMO, as long as the algorithm can be expressed clearly & concisely.

**Comment by sorear** [comment]
So:

1. If an argument has 2 or fewer float fields of ≤FLEN, and there are enough free FPRs, pass in an FPR.
2. If an argument is > 2 * XLEN, pass it in read-only caller allocated memory, replace the argument with a pointer, *and continue*
3. If an argument has exactly 1 integer field and there is a GPR free, pass in that GPR after type-extending to 32 bits and sign-extending from 32 bits to XLEN
4. Otherwise pack the argument into 0–2 GPRs and pass in GPRs if there are enough free
5. Otherwise pass on the stack

?

How is va_list handled?  If passing struct { long; long; } sometimes leaves a hole in a7 that sounds like a complication.

**Comment by aswaterman** [comment]
Definitely shouldn't have a hole at a7 in an unnamed argument in the varags case.  It's of course OK if the passing convention for unnamed arguments differs from the named-parameter passing convention.  (The varags calling convention should be simple for the callee to achieve reasonable runtime performance, so inherently it should be reasonably simple to spec.)

Your description seems to match my proposal.  I need to think about it more carefully and do some benchmarking, though.  It's important we get this right, since this is probably our last good chance to change it.

**Comment by kito-cheng** [comment]
Push all vaargs to stack by caller is an option too, it's simpler and vaarg is not performance critical part in general case.

**Comment by aswaterman** [comment]
Yeah, I was going to evaluate the code size of that option, too.

**Comment by sorear** [comment]
If you can figure out how, I'd also like to see a comparison between s390 / amd64 struct arguments.  Making the callee copy saves effort if the caller wasn't going to modify the argument anyway (or take a & reference…), making the caller copy saves effort if the struct is a temporary which doesn't need to be preserved, and I can't determine from first principles which is better.

**Comment by aswaterman** [comment]
@kito-cheng any idea how you inform gcc who "owns" arguments passed on the stack?  It seems that they belong to the caller for s390 (i.e., they are are callee-saved).

**Comment by aswaterman** [comment]
Passing all varargs on the stack has the downside that you can't tail-call a varargs function (e.g., if printf is the last statement in a subroutine).  This increases stack usage further and might have a more profound impact on code size than the extra arg-pushing.

Net code size increase is 0.2% for my sysroot and 0.5% for SPEC.  That's a fairly large regression, so let's not go that route.

**Comment by aswaterman** [comment]
In my recent proposal, _Complex types are treated the same as structs with two floats, i.e., passed in FP registers if possible.
