### ISSUE TITLE
Sign extension of int when passing int+fp struct?

### ISSUE THREAD

**Issue by asb** [riscv/riscv-elf-psabi-doc#37]
When using the hard FP ABI, a struct containing just an int+fp may be passed in one GPR and one FPR. If the integer is < XLEN, is its extension to XLEN bits specified? i.e. is it passed as if it were a scalar parameter (extended according to the sign of the type up to 32-bits, then sign extended to XLEN), or are the bits beyond the width of the original type undefined?

**Comment by palmer-dabbelt** [comment]
It should be passed just like a scalar.
