### ISSUE TITLE
Calling convention weirdness: mixed struct returns

### ISSUE THREAD

**Issue by sorear** [riscv/riscv-elf-psabi-doc#4]
A `struct { double x; long y; }` is passed in a GPR and a FPR on call, but in two GPRs on return. It'd be didactically useful for have the rules for return values be precisely the same as for call arguments.

**Comment by aswaterman** [comment]
Agreed.

**Comment by aswaterman** [comment]
AArch64 and x86-64 are both self-consistent here.  The former chooses to both pass and return in an integer register pair.  The latter uses an SSE and an integer register for both call and return.

For struct{float;int}, they both pass and return the entire struct in a single integer register.  (Still self-consistent, but hard to believe it's the performant thing to do.)

**Comment by aswaterman** [comment]
My recent proposal addresses this (the G calling convention will pass and return this struct in fa0 + a0).
