### ISSUE TITLE
long double in structs, call/return inconsistency

### ISSUE THREAD

**Issue by sorear** [riscv/riscv-elf-psabi-doc#5]
Nested structs with long doubles (more generally: float types = 2 * XLEN > FLEN) and other zero-byte fields are in some cases passed in GPR pairs.  It'd be simpler if we could say that anything with a real long double field (in particular, not a zero-length array of long double) is forced to memory passing.

**Comment by aswaterman** [comment]
That would seem to make the calling convention more complicated, because it adds a special case.  But it seems likely to be higher performance.

**Comment by aswaterman** [comment]
I believe that the resolution to #6 makes this issue mostly moot.  Are we screwing up the passing of other kinds of zero-byte fields?

**Comment by sorear** [comment]
The problem here isn't with the zero-byte fields per se, it's that there are several ways to make a struct which is functionally equivalent to a long double and not all of them wind up marked TFmode.  This is indeed moot if we're getting rid of the long double exception.
