### ISSUE TITLE
Customized relocation type

### ISSUE THREAD

**Issue by wuiw** [riscv/riscv-elf-psabi-doc#64]
In our current CPU design, we extend RISC-V ISA by adding several instructions, such as GP-implied load/store. To handle these instructions, we also extend relocation type. However, there does not have any rule or guideline to add customized relocation type currently. To avid conflict, in our current design, the new relocation id is assigned from 255 and in decreasing order. Could anyone have any idea or propose to deal with this issue?

**Comment by aswaterman** [comment]
I agree we should reserve a block of relocations for nonstandard extensions to the ABI.  @palmer-dabbelt @asb any objections with reserving 192-255 for this purpose?

**Comment by asb** [comment]
No objections, we should reserve some space for non-standard relocations.

The other missing piece is metadata in the ELF which describes the non-standard extensions which are targeted. Kito was hoping to propose something for that, based on the discussion in #47.

**Comment by aswaterman** [comment]
Indeed.  Whatever the solution to #47 might be, it should also provide enough information to decode what the nonstandard relocs mean.

**Comment by kito-cheng** [comment]
BTW #47 is getting higher priority to me, I am working on implement that on biinutils now, and I've changed to implement an attribute section (ref [1] ELF for the ARM® Architecture, 4.3.6 Build Attributes).

[1] http://infocenter.arm.com/help/topic/com.arm.doc.ihi0044f/IHI0044F_aaelf.pdf

**Comment by aswaterman** [comment]
Cool.  @jim-wilson are there any lessons to be learned from using the ARM attribute section?

**Comment by jim-wilson** [comment]
They were already implemented before I started doing ARM work, so I don't have any direct experiences with development issues.  I've only dealt with them as a user, and have found them useful.  There are other targets with attribute support besides ARM, and I think we can just use the generic binutils support for this, customized with RISC-V specific hooks.  Though the generic attribute support is based on the ARM support, as I think the ARM target was the first to do this.
