### ISSUE TITLE
Classes with virtual methods appear to be forced to pass in memory

### ISSUE THREAD

**Issue by sorear** [riscv/riscv-elf-psabi-doc#7]
http://refspecs.linuxbase.org/cxxabi-1.83.html#calls implies that classes without nontrivial copy constructors are supposed to be handled like structs, but this code is passing a one-word class in memory:

```
class A {
public:
virtual void fn();
};

extern void abc(A);
void cba() { A q; abc(q); }
```

**Comment by aswaterman** [comment]
It looks like the Itanium C++ ABI requires that classes with nontrivial copy constructors be passed by reference: https://mentorembedded.github.io/cxx-abi/abi.html#value-parameter

**Comment by sorear** [comment]
My example doesn't have a nontrivial copy construction, but it's being treated as if it did.

**Comment by aswaterman** [comment]
Ah, right, I misunderstood you.  Anyway, x86-64 and AArch64 have the same idiosyncrasy as we do.  Can you check their ABI specs and see if you can uncover the explanation?

**Comment by sorear** [comment]
The footnote on https://uclibc.org/docs/psABI-x86_64.pdf#page=20 provides a non-obvious technical definition of "nontrivial copy constructor", so we're doing the right thing.

**Comment by aswaterman** [comment]
Interesting, thanks for the detective work.
