### ISSUE TITLE
DWARF register mappings

### ISSUE THREAD

**Issue by alexrp** [riscv/riscv-elf-psabi-doc#70]
The [DWARF specification](http://www.dwarfstd.org/doc/DWARF4.pdf) says that ABI implementations should define the hardware register -> DWARF register mappings (§2.6.1.1.2). It seems that this is not included in the RISC-V psABI, nor can I seem to find this mapping anywhere else in official RISC-V documentation. As an example, the [x86-64 psABI](http://refspecs.linuxfoundation.org/elf/x86_64-abi-0.95.pdf) documents the register mapping in §3.6.2.

For context, this is needed in [Mono](https://github.com/mono/mono) to do unwinding. E.g. for x86-64: https://github.com/mono/mono/blob/aec2773e1db0799479161688d6161f5d5ce586a3/mono/mini/unwind.c#L46-L51

**Comment by jim-wilson** [comment]
We don't have an official gdb port yet, so these numbers probably aren't finalized yet.

GCC uses 0-31 for the integer registers, 32-63 for the FP registers, and then 64 is the alternate return address column used for the return address in signal handlers.  GCC does not support CSRs.  GDB uses 0-31 for the integer registers, 32 for the pc, 33-64 for the FP registers, and 65+ are CSRs, e.g. ustatus is 65.

That leads to the obvious question of how can this work if gcc and gdb are using different numbers for FP registers.  I don't know if it does, but I don't have any easy way to check.  The gdb port I'm looking at is not the one that was just submitted upstream a couple of days ago though, so it is possible that gdb may have been changed already, and this might have been fixed already.  If gdb isn't already fixed, and if this isn't already working some how, then at some point we will have to change gcc and/or gdb to make this work.

So you should not make any assumptions at this time as to what the dwarf register mapping is.

**Comment by aswaterman** [comment]
Isn't the DWARF register mapping already baked into the ABI because of C++ exception handling?

**Comment by jim-wilson** [comment]
Yes, changing gcc would cause a lot more trouble than changing gdb, because changing gcc would break stuff like C++ exception handling.

**Comment by alexrp** [comment]
OK, so given that the register mapping in GCC is already part of the C++ ABI, using that in Mono sounds reasonable enough, at least until things stabilize.

By the way, could you point me to the relevant GCC/GDB sources that define those register mappings for RISC-V?

**Comment by jim-wilson** [comment]
On Fri, Feb 16, 2018 at 3:41 PM, Alex Rønne Petersen <
notifications@github.com> wrote:

> OK, so given that the register mapping in GCC is already part of the C++
> ABI, using that in Mono sounds reasonable enough, at least until things
> stabilize.
>
> By the way, could you point me to the relevant GCC/GDB sources that define
> those register mappings for RISC-V?
>
GCC is upstream at gcc.gnu.org.  In the gcc/config/riscv/riscv.h file it
has DWARF_FRAME_REGNUM which just returns the gcc internal register
number.  The gcc internal register numbers can be seen in the GP_REG_FIRST,
GP_REG_LAST, FP_REG_FIRST, and FP_REG_LAST macros.  There is also a
DWARF_ALT_FRAME_RETURN_COLUMN macro set to 64, which is used in signal
handlers for the return address.

GDB is not upstream, though a patch was just posted a few days ago to the
gdb-patches mailing list.  You can also find a port, which is probably not
the same code submitted for upstream, in the github
riscv/riscv-binutils-gdb project tree.  Looking at the github tree, in the
gdb/riscv-tdep.h file, there is an unnamed enum that starts with
RISCV_ZERO_REGNUM followed by the rest of the gp regs, then has
RISCV_PC_REGNUM as 32, followed by the fp regs, followed by the csrs.  Then
there is a RISCV_PRIV_SPEC register after the last csr, which holds info on
whether you are in user or supervisor or machine mode.

Jim

**Comment by alexrp** [comment]
Perfect, thank you!

**Comment by jim-wilson** [comment]
GDB defines an enum in riscv-tdep.h.
/* RiscV DWARF register numbers.  */
enum
{
  RISCV_DWARF_REGNUM_X0 = 0,
  RISCV_DWARF_REGNUM_X31 = 31,
  RISCV_DWARF_REGNUM_F0 = 32,
  RISCV_DWARF_REGNUM_F31 = 63,
};
and in riscv-tdep.c has a function riscv_dwarf_reg_to_regnum that does the conversion from dwarf register numbers to gdb internal register numbers, though for now these happen to be the same numbers.

**Comment by jim-wilson** [comment]
Fixed.
