### ISSUE TITLE
Two clarifications.

### ISSUE THREAD

**Issue by ragge0** [riscv/riscv-elf-psabi-doc#78]
Hi,

I assume that packed structs are always passed on the stack?  Can't find it documented?

Also, an RV32IMAD (no F extension), should it still have float arguments in float registers?  (Unlikely combination, but should be documented).

**Comment by asb** [comment]
https://github.com/riscv/riscv-elf-psabi-doc/pull/75 was reviewed but not merged, and documents the treatment of packed structs. There's possibly room for clarifying the treatment of packed structs under the integer calling convention, but I believe the description of the rules for passing aggregates under the Integer Calling Convention section is sufficient.

RV32IMAD is not a valid configuration, see Chapter 10 of the user-level ISA spec "The D extension depends on the base single-precision instruction subset F."

**Comment by ragge0** [comment]
Great, thanks!
