### ISSUE TITLE
Clarification For Empty Struct Handling in C++

### ISSUE THREAD

**Issue by T-J-Teru** [riscv/riscv-elf-psabi-doc#88]
This issue is about my interpretation of the ABI and GCC's implementation of the ABI.  GCC is definitely broken in one specific case, but what the fix is depends on the ABI, and it's not obvious to me exactly what the existing text means.

Lets start with an example of what GCC does wrong, this is actually a C++ test, not C, that is important:

```
#define MAKE_STRUCT_PASSING_TEST(type,val)                              \
  static struct struct_ ## type ## _t                                   \
  {                                                                     \
    struct { } e;                                                       \
    struct { type f; } s;                                               \
  } global_struct_ ## type = { {}, { val } };                           \
                                                                        \
  static bool                                                           \
  check_struct_ ## type (struct_ ## type ## _t obj)                     \
  {                                                                     \
    return (obj.s.f == global_struct_ ## type .s.f);                    \
  }                                                                     \
                                                                        \
  int                                                                   \
  main ()                                                               \
  {                                                                     \
    bool result = check_struct_ ## type ( global_struct_ ## type );     \
    return result ? 0 : 1;                                              \
  }

MAKE_STRUCT_PASSING_TEST(float,2.5)
```

The relevant part of the ABI document is this:

> Empty structs or union arguments or return values are ignored by C compilers which support them as a non-standard extension. This is not the case for C++, which requires them to be sized types.

As I said, this is a C++ test, so the empty sub-struct will have size 1-byte, but with trailing padding will account for 4-bytes in the containing struct.

Currently GCC is a bit of a mess in its handling of these cases.  In the example above with a float argument GCC tries to ignore the empty struct, but then incorrectly passes the float field (it actually passes the empty struct instead).  If the above example is changed to contain an integer field then GCC correctly passes the full struct, including the empty part and the integer field using two integer registers.

The quoted part of the ABI document doesn't really say _what_ should happen with empty C++ structs, it seems to me the ABI document simply states that such structures are non-zero sized, which is true.

However, as far as I understand it, the content of that non-zero sized space is undefined, and as such a compiler _could_ ignore the empty structure in C++ just as it does in C.

In the above case the caller could pass the non-empty fields and the callee can simply make up content with which to fill the non-zero sized empty struct, this feels just as valid as passing over some undefined bytes.

I currently see two routes forward, one would be we change the above quoted part to read something like:

> Empty structs or union arguments or return values are ignored by C compilers which support them as a non-standard extension. In C++ empty structs and unions are required to be sized types, however, as their content is undefined, they are similarly ignored when passing arguments.

We then fix GCC  to correctly ignore the empty structs in C++, this would fix the float case which is just broken, but would be ABI breaking in GCC for the case of passing an empty struct and an integer.

Alternatively, we make the intention of the ABI clearer by changing the above quoted text to read something like:

> Empty structs or union arguments or return values are ignored by C compilers which support them as a non-standard extension. This is not the case for C++, which requires them to be sized types, and these are passed as integer arguments.

We then fix GCC to correctly pass over the empty structs in C++, this would fix the float case which is currently just broken, and would maintain the existing ABI in GCC for the integer case.  However, the final ABI would be slightly less efficient in this case (which is probably an edge case anyway, so we probably don't care too much about efficiency).

**Comment by jim-wilson** [comment]
The main problem with gcc for the testcase is that we assume the in-struct offset is always zero when we have a single float arg.  Though now that I look at the issue, I see you already came to the same conclusion and wrote a similar patch.

I think the handling for empty structs should stay the same, as there is no bug there.  The text you quoted only applies to an empty struct.  It does not apply to an empty struct inside another struct.

If there is an issue, it would be in the text for flattening structures.  However, this text already says
```Fields containing empty structs or unions are ignored while flattening, even in C++, unless they have nontrivial copy constructors or destructors. ```
So gcc does seem to be implementing this correctly.

We only flatten an aggregate when it contains at least one float field, and an empty struct plus an integer doesn't qualify, so we don't need any change to the ABI for this case.

Thus all we need to fix is a gcc bug where it is getting the float field offset wrong when we have empty struct plus float.  Since this case is already broken, it isn't really an ABI change, it is just a bug fix, and doesn't need any special handling.

**Comment by T-J-Teru** [comment]
Jim, thanks for the explanation.  I admit I hadn't spotted that the flattening only happens when passing floats.  I can imagine how that situation has arrived.  I'll post a patch for GCC shortly to fix the float offset case.

I wonder if it is worth adding some words to the "Integer Calling Convention" explicitly stating that empty structures are never flattened in the integer only case, and thus when using C++ this will result in empty space being passed around.  Though its correct that with no words this should be the assumed default, this makes the integer ABI slightly less efficient than the float ABI, and so isn't (to me anyway) the "obvious" choice.

> The Floating Point ABI (see below) describes a strategy for flattening structures in order to more efficiently pass values in floating point registers.  Any structure not covered by the Float Point ABI flattening rules is not flattened, and is passed as a standard structure.  When considering empty sub-structures in C++, this means that the space associated with the empty structure can be passed in a register.

**Comment by jim-wilson** [comment]
I don't see the need to clarify the int docs.  The int docs don't do flattening, so we don't need to document that.  They also don't use FP regs, and we don't document that either.  You usually don't need to document something that doesn't exist.

The int docs say "Aggregates whose total size is no more than XLEN bits are passed in a register, with the fields laid out as though they were passed in memory. "  Whether or not one of the fields is an empty structure is irrelevant.  It doesn't change how the aggregate is passed.

I don't feel strongly about this though.  If other people think this is helpful we can add it into the docs.

**Comment by asb** [comment]
I don't feel particularly strongly about this either. The fact that flattening doesn't happen for the integer ABI seemed clear to me, but once you've spent long enough with the spec it becomes pretty hard to judge what is obvious/non-obvious.

I think something along the lines of the clarification suggested seems ok. I question if it's needed but like Jim don't feel strongly about it.

**Comment by aswaterman** [comment]
I'd suggest erring on the side of parsimony.

**Comment by jim-wilson** [comment]
FYI we now coincidentally have a FSF GCC bug report.
    https://gcc.gnu.org/bugzilla/show_bug.cgi?id=89627
Unlike Andrew's testcase, this one looks like real code.

**Comment by jim-wilson** [comment]
No one seems in favor of extending the docs here, so I propose closing this.
