### ISSUE TITLE
about Calling Convention

### ISSUE THREAD

**Issue by amwyga** [riscv/riscv-elf-psabi-doc#91]
RISC-V Integer Calling Convention in web site:"https://github.com/riscv/riscv-elf-psabi-doc/blob/master/riscv-elf.md" says that "Aggregates whose total size is no more than XLEN bits are passed in a register, with the fields laid out as though they were passed in memory. If no register is available, the aggregate is passed on the stack. Aggregates whose total size is no more than 2✕XLEN bits are passed in a pair of registers".
Does this mean that the aggregate type of more than 2✕XLEN must be placed on the stack according to the RISC-V calling specification? so the Calling Convention seems to conflict with the code generated by GCC's -fipa-sra optimization option, as this option may use more than two registers when converting aggregate types to scalars. So, does this mean that the use of RISC-V should disable the -fipa-sra option?

**Comment by jim-wilson** [comment]
This was cross posted to both riscv-gcc #155 and riscv-elf-psabi-doc #91.

No, the gcc -fipa-sra option is not violating the ABI.  There are multiple ways to look at this.

1) The ABI documents the external interface to an object file.  A compiler is free to choose a different interface for functions internal to an object file.
2) The compiler is changing the function type signature, from one with a struct arg to one with multiple scalar args, and then using the standard ABI on the new type signature.

Either way you look at this, it is invisible to the programmer, as the compiler ensures that everything is correct, and emits appropriate DWARF2 debug info to make the new function type look like the old one.

**Comment by amwyga** [comment]
this means that if the function is local, you can not follow the calling convention at all. as long as the program is correct, the compiler can decide how to use all the registers, right?

**Comment by amwyga** [comment]
> This was cross posted to both riscv-gcc #155 and riscv-elf-psabi-doc #91.
> 
> No, the gcc -fipa-sra option is not violating the ABI. There are multiple ways to look at this.
> 
> 1. The ABI documents the external interface to an object file.  A compiler is free to choose a different interface for functions internal to an object file.
> 2. The compiler is changing the function type signature, from one with a struct arg to one with multiple scalar args, and then using the standard ABI on the new type signature.
> 
> Either way you look at this, it is invisible to the programmer, as the compiler ensures that everything is correct, and emits appropriate DWARF2 debug info to make the new function type look like the old one.

this means that if the function is local, you can not follow the calling convention at all. as long as the program is correct, the compiler can decide how to use all the registers, right?

**Comment by amwyga** [comment]
> This was cross posted to both riscv-gcc #155 and riscv-elf-psabi-doc #91.
> 
> No, the gcc -fipa-sra option is not violating the ABI. There are multiple ways to look at this.
> 
> 1. The ABI documents the external interface to an object file.  A compiler is free to choose a different interface for functions internal to an object file.
> 2. The compiler is changing the function type signature, from one with a struct arg to one with multiple scalar args, and then using the standard ABI on the new type signature.
> 
> Either way you look at this, it is invisible to the programmer, as the compiler ensures that everything is correct, and emits appropriate DWARF2 debug info to make the new function type look like the old one.

this means that if the function is local, you can not follow the calling convention at all. as long as the program is correct, the compiler can decide how to use all the registers, right?

so if the function is local,  it is detected in advance that the number of CALLEE registers used in the called function is less than the total number of hardware CALLEE registers, the compiler may also use CALLEE registers or temporary registers for function parameter passing?

**Comment by amwyga** [comment]
> This was cross posted to both riscv-gcc #155 and riscv-elf-psabi-doc #91.
> 
> No, the gcc -fipa-sra option is not violating the ABI. There are multiple ways to look at this.
> 
> 1. The ABI documents the external interface to an object file.  A compiler is free to choose a different interface for functions internal to an object file.
> 2. The compiler is changing the function type signature, from one with a struct arg to one with multiple scalar args, and then using the standard ABI on the new type signature.
> 
> Either way you look at this, it is invisible to the programmer, as the compiler ensures that everything is correct, and emits appropriate DWARF2 debug info to make the new function type look like the old one.

this means that if the function is local, you can not follow the calling convention at all. as long as the program is correct, the compiler can decide how to use all the registers, right?

example:
    so if the function is local, it is detected in advance that the number of CALLEE registers used in the called function is less than the total number of hardware CALLEE registers, the compiler may also use CALLEE registers or temporary registers for function parameter passing?

**Comment by amwyga** [comment]
> This was cross posted to both riscv-gcc #155 and riscv-elf-psabi-doc #91.
> 
> No, the gcc -fipa-sra option is not violating the ABI. There are multiple ways to look at this.
> 
> 1. The ABI documents the external interface to an object file.  A compiler is free to choose a different interface for functions internal to an object file.
> 2. The compiler is changing the function type signature, from one with a struct arg to one with multiple scalar args, and then using the standard ABI on the new type signature.
> 
> Either way you look at this, it is invisible to the programmer, as the compiler ensures that everything is correct, and emits appropriate DWARF2 debug info to make the new function type look like the old one.

this means that if the function is local, you can not follow the calling convention at all. as long as the program is correct, the compiler can decide how to use all the registers, right?

example:
so if the function is local, it is detected in advance that the number of CALLEE registers used in the called function is less than the total number of hardware CALLEE registers, the compiler may also use CALLEE registers  for function parameter passing?

**Comment by kito-cheng** [comment]
> so if the function is local, it is detected in advance that the number of CALLEE registers used in the called function is less than the total number of hardware CALLEE registers, the compiler may also use CALLEE registers or temporary registers for function parameter passing?

Yeah, compiler might use other than a0-a7 to pass register, IIRC it will happen in LLVM for local functions.

**Comment by amwyga** [comment]
> > so if the function is local, it is detected in advance that the number of CALLEE registers used in the called function is less than the total number of hardware CALLEE registers, the compiler may also use CALLEE registers or temporary registers for function parameter passing?
> 
> Yeah, compiler might use other than a0-a7 to pass register, IIRC it will happen in LLVM for local functions.

has the 8.0 version of the latest release of LLVM been implemented? or included in the 9.0 version of the implementation plan

**Comment by asb** [comment]
> > > so if the function is local, it is detected in advance that the number of CALLEE registers used in the called function is less than the total number of hardware CALLEE registers, the compiler may also use CALLEE registers or temporary registers for function parameter passing?
> > 
> > 
> > Yeah, compiler might use other than a0-a7 to pass register, IIRC it will happen in LLVM for local functions.
> 
> has the 8.0 version of the latest release of LLVM been implemented? or included in the 9.0 version of the implementation plan

8.0 includes substantial RISC-V support, but it is not compiled by default (we are still an "experimental" backend). We intend to become non-experimental in the 9.0 release cycle.
